### ISSUE TITLE
Transpose an Excel range into a Word document

### ISSUE THREAD

**Issue by lpazzeto** [sancarn/vba-articles#6]
I am struggling with the following code:

Sub UpdateWordDocument()
    Dim wordApp As Object
    Dim wordDoc As Object
    Dim rng As Range
    Dim rowNumber As Integer

    ' Set the row number to the last used row in column C
    rowNumber = ThisWorkbook.Sheets("Sheet1").Cells(ThisWorkbook.Sheets("Sheet1").Rows.Count, "C").End(xlUp).Row

    ' Set the range containing data (columns C to E, rowNumber)
    Set rng = ThisWorkbook.Sheets("Sheet1").Range("C3:E" & rowNumber)

    ' Create a new Word application instance
    Set wordApp = CreateObject("Word.Application")
    wordApp.Visible = True ' Set this to True if you want to see Word application

    ' Open the Word document
    Set wordDoc = wordApp.Documents.Open("C:\Users\Dell\Downloads\TESTE\Document.docx") ' Change the file path

    ' Insert data from Excel range into Word document at the bookmark
    wordDoc.ContentControl("tab_reneg1").Range.Text = Join(Application.WorksheetFunction.Transpose(rng.Value), vbTab)

    ' Clean up
    Set wordDoc = Nothing
    Set wordApp = Nothing
End Sub

My task is to input the Excel range as a table into the Word document. But everytime VBA reaches the statement "    wordDoc.ContentControl("tab_reneg1").Range.Text = Join(Application.WorksheetFunction.Transpose(rng.Value), vbTab)"

I get the error: "Invalid procedure call or argument"

I checked the Content Control name and it is correct.

**Comment by sancarn** [comment]
Hi, sorry but this isn't the right forum for this. Please ask on [reddit](https://reddit.com/r/vba) or [discord](https://discord.gg/DgkBuBU9)
